version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  test:
    docker:
      - image: circleci/node:6-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: pwd
      - run: ls
      - run: npm test
      - store_artifacts:
          path: ~/repo/coverage/lcov.info
          destination: coverage

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build